#!/usr/bin/env python

# (py resfromdy.py >! plots/out.resfromdy) && tlp plots/*resfromdy

import os
import ROOT
import math
from array import array
from ROOT import *
#from SUSYBSMAnalysis.Zprime2muAnalysis.roottools import *
#set_zp2mu_style()
#ROOT.gStyle.SetOptFit(1111)
gStyle.SetOptStat("")

ROOT.gStyle.SetPadTopMargin(0.02)
ROOT.gStyle.SetPadRightMargin(0.02)

###################################################################
def PaintOverflow(h, opt=''):
    #This function paint the histogram h with an extra bin for overflows
    name  = h.GetName()
    print name
    title = h.GetTitle()
    nx    = h.GetNbinsX()+1
    x1    = h.GetBinLowEdge(1)
    bw    = h.GetBinWidth(nx)
    x2    = h.GetBinLowEdge(nx)+bw
    print nx, x1, bw, x2
    htmp  = ROOT.TH1F(name, title, nx, x1, x2)
    for i in xrange(1, nx+1):
        htmp.Fill(htmp.GetBinCenter(i), h.GetBinContent(i))
        #print h.GetBinContent(i)
    htmp.Fill(x1-1, h.GetBinContent(0))
    htmp.SetEntries(h.GetEntries())
    return htmp
#    c_tmp = ROOT.TCanvas( 'c_tmp', '')
#    htmp.Draw(opt)
#    t = ROOT.TText(x2-bw/2,h.GetBinContent(nx),"Overflow")
#    t.SetTextAngle(90)
#    t.SetTextAlign(12)
#    t.SetTextSize(0.03)
#    t.Draw("same")
#    c_tmp.Print('tmp.pdf')


###################################################################
f1tev_at8tev = ROOT.TFile('./files/zp2mu_dy1500_8.root')
d1tev_at8tev = f1tev_at8tev.HistosVertexFromPAT
h1tev_at8tev = d1tev_at8tev.Get('DimuonMassVertexConstrained')
h1tev_at8tev_LeptonEta = d1tev_at8tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at8tev_LeptonEta_MassRange = d1tev_at8tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at8tev_Nvtx = d1tev_at8tev.Get('NVertices')

h1tev_at8tev_chi = d1tev_at8tev.Get('DimuonMassVtx_chi2')
h1tev_at8tev_prob = d1tev_at8tev.Get('DimuonMassVtx_prob')
h1tev_at8tev_MuonProb = d1tev_at8tev.Get('DimuonMuonPtProb')
h1tev_at8tev_MuonPtErrOverPt = d1tev_at8tev.Get('DimuonMuonPtErrOverPt')

h1tev_at8tev_MuonProbB = d1tev_at8tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at8tev_MuonProbE = d1tev_at8tev.Get('DimuonMuonPtProb_Endcap')
h1tev_at8tev_MuonProbB_MassRange = d1tev_at8tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at8tev_MuonProbE_MassRange = d1tev_at8tev.Get('DimuonMuonPtProb_Endcap')

h1tev_at8tev_MuonPtErrorB = d1tev_at8tev.Get('DimuonMuonPtError_Barrel')
h1tev_at8tev_MuonPtErrorE = d1tev_at8tev.Get('DimuonMuonPtError_Endcap')
h1tev_at8tev_MuonPtErrorOverPtB_MassRange = d1tev_at8tev.Get('DimuonMuonPtErrOverPt_Barrel')
h1tev_at8tev_MuonPtErrorOverPtE_MassRange = d1tev_at8tev.Get('DimuonMuonPtErrOverPt_Endcap')

h1tev_at8tev_prob_BB = d1tev_at8tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at8tev_prob_EE = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at8tev_prob_EB = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapBarrel')
h1tev_at8tev_prob_BB_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at8tev_prob_EE_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at8tev_prob_EB_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapBarrel')

#h1tev_at8tev_d0B = d1tev_at8tev.Get('TrackD0PV_Barrel')
#h1tev_at8tev_d0E = d1tev_at8tev.Get('TrackD0PV_Endcap')
h1tev_at8tev_d0B = d1tev_at8tev.Get('TrackD0BS_Barrel')
h1tev_at8tev_d0E = d1tev_at8tev.Get('TrackD0BS_Endcap')

h1tev_at8tev_iterB = d1tev_at8tev.Get('TrackIteration_Barrel')
h1tev_at8tev_iterE = d1tev_at8tev.Get('TrackIteration_Endcap')

h1tev_at8tev_iterVSprobB = d1tev_at8tev.Get('TrackIterationVSPtProb_Barrel')
h1tev_at8tev_iterVSprobE = d1tev_at8tev.Get('TrackIterationVSPtProb_Endcap')

h1tev_at8tev_iterVSvtxprobEE = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob_EndcapEndcap')
h1tev_at8tev_iterVSvtxprobEB = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob_EndcapBarrel')
h1tev_at8tev_iterVSvtxprobBB = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob_BarrelBarrel')
h1tev_at8tev_newiterVSvtxprobEE = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob1314_EndcapEndcap')
h1tev_at8tev_newiterVSvtxprobEB = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob1314_EndcapBarrel')
h1tev_at8tev_newiterVSvtxprobBB = d1tev_at8tev.Get('TrackIterationVSDimuonMassVtx_prob1314_BarrelBarrel')


##################

f1tev_at13tev = ROOT.TFile('./files/zp2mu_dy1500_13.root')
d1tev_at13tev = f1tev_at13tev.HistosVertexFromPAT
h1tev_at13tev = d1tev_at13tev.Get('DimuonMassVertexConstrained')
h1tev_at13tev_LeptonEta = d1tev_at13tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at13tev_LeptonEta_MassRange = d1tev_at13tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at13tev_Nvtx = d1tev_at13tev.Get('NVertices')

h1tev_at13tev_chi = d1tev_at13tev.Get('DimuonMassVtx_chi2')
h1tev_at13tev_prob = d1tev_at13tev.Get('DimuonMassVtx_prob')
h1tev_at13tev_MuonProb = d1tev_at13tev.Get('DimuonMuonPtProb')
h1tev_at13tev_MuonPtErrOverPt = d1tev_at13tev.Get('DimuonMuonPtErrOverPt')

h1tev_at13tev_MuonProbB = d1tev_at13tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at13tev_MuonProbE = d1tev_at13tev.Get('DimuonMuonPtProb_Endcap')
h1tev_at13tev_MuonProbB_MassRange = d1tev_at13tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at13tev_MuonProbE_MassRange = d1tev_at13tev.Get('DimuonMuonPtProb_Endcap')

h1tev_at13tev_MuonPtErrorB = d1tev_at13tev.Get('DimuonMuonPtError_Barrel')
h1tev_at13tev_MuonPtErrorE = d1tev_at13tev.Get('DimuonMuonPtError_Endcap')
h1tev_at13tev_MuonPtErrorOverPtB_MassRange = d1tev_at13tev.Get('DimuonMuonPtErrOverPt_Barrel')
h1tev_at13tev_MuonPtErrorOverPtE_MassRange = d1tev_at13tev.Get('DimuonMuonPtErrOverPt_Endcap')

h1tev_at13tev_prob_BB = d1tev_at13tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at13tev_prob_EE = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at13tev_prob_EB = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapBarrel')
h1tev_at13tev_prob_BB_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at13tev_prob_EE_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at13tev_prob_EB_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapBarrel')

#h1tev_at13tev_d0B = d1tev_at13tev.Get('TrackD0PV_Barrel')
#h1tev_at13tev_d0E = d1tev_at13tev.Get('TrackD0PV_Endcap')
h1tev_at13tev_d0B = d1tev_at13tev.Get('TrackD0BS_Barrel')
h1tev_at13tev_d0E = d1tev_at13tev.Get('TrackD0BS_Endcap')

h1tev_at13tev_iterB = d1tev_at13tev.Get('TrackIteration_Barrel')
h1tev_at13tev_iterE = d1tev_at13tev.Get('TrackIteration_Endcap')

h1tev_at13tev_iterVSprobB = d1tev_at13tev.Get('TrackIterationVSPtProb_Barrel')
h1tev_at13tev_iterVSprobE = d1tev_at13tev.Get('TrackIterationVSPtProb_Endcap')

h1tev_at13tev_iterVSvtxprobEE = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob_EndcapEndcap')
h1tev_at13tev_iterVSvtxprobEB = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob_EndcapBarrel')
h1tev_at13tev_iterVSvtxprobBB = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob_BarrelBarrel')
h1tev_at13tev_newiterVSvtxprobEE = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob1314_EndcapEndcap')
h1tev_at13tev_newiterVSvtxprobEB = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob1314_EndcapBarrel')
h1tev_at13tev_newiterVSvtxprobBB = d1tev_at13tev.Get('TrackIterationVSDimuonMassVtx_prob1314_BarrelBarrel')

#h5tev = fit_gaussian(h5tev,None,True)
#h5tev = fit_gaussian(h5tev,None,True)

# Legend:
leg = ROOT.TLegend( 0.65, 0.75, 0.9, 0.9 )
leg.SetFillColor(kWhite)
leg.SetLineColor(kWhite)
leg.SetTextSize(0.03)
leg.AddEntry(h1tev_at8tev, " DY 1.5TeV @ 8TeV", "L")
leg.AddEntry(h1tev_at13tev, " DY 1.5TeV @ 13TeV", "L")


c_mass = ROOT.TCanvas( 'c_mass', '')
h1tev_at8tev.Scale(1/h1tev_at8tev.Integral())
h1tev_at13tev.Scale(1/h1tev_at13tev.Integral())
#h5tev.Rebin(10)
h1tev_at8tev.Rebin(10)
h1tev_at13tev.Rebin(10)

h1tev_at8tev.SetLineColor(1)
h1tev_at8tev.SetLineWidth(2)
h1tev_at13tev.SetLineColor(2)
h1tev_at13tev.SetLineWidth(2)

h1tev_at8tev.GetYaxis().SetRangeUser(0, 0.24)
#h1tev_at13tev.GetYaxis().SetRangeUser(0, 0.08)
h1tev_at8tev.GetXaxis().SetRangeUser(0, 4000)
h1tev_at13tev.GetXaxis().SetRangeUser(0, 4000)
h1tev_at8tev.Draw("histo")
h1tev_at13tev.Draw("same histo")
leg.Draw()
c_mass.Print('DYsuperimposition_mass.pdf')

c_scat = ROOT.TCanvas( 'c_scat', '')
pad1 = TPad( 'pad1', '', 0.03, 0.66, 0.48, 0.98)
pad2 = TPad( 'pad2', '', 0.50, 0.66, 0.98, 0.98)
pad3 = TPad( 'pad3', '', 0.03, 0.33, 0.48, 0.64)
pad4 = TPad( 'pad4', '', 0.50, 0.33, 0.98, 0.64)
pad5 = TPad( 'pad5', '', 0.03, 0.02, 0.48, 0.32)
pad6 = TPad( 'pad6', '', 0.50, 0.02, 0.98, 0.32)
pad1.Draw()
pad2.Draw()
pad3.Draw()
pad4.Draw()
pad5.Draw()
pad6.Draw()
h1tev_at13tev_iterVSvtxprobEE.Rebin2D(1,20)
h1tev_at13tev_iterVSvtxprobEB.Rebin2D(1,20)
h1tev_at13tev_iterVSvtxprobBB.Rebin2D(1,20)
h1tev_at13tev_newiterVSvtxprobEE.Rebin2D(1,20)
h1tev_at13tev_newiterVSvtxprobEB.Rebin2D(1,20)
h1tev_at13tev_newiterVSvtxprobBB.Rebin2D(1,20)
h1tev_at8tev_iterVSvtxprobEE.Rebin2D(1,20)
h1tev_at8tev_iterVSvtxprobEB.Rebin2D(1,20)
h1tev_at8tev_iterVSvtxprobBB.Rebin2D(1,20)
h1tev_at8tev_newiterVSvtxprobEE.Rebin2D(1,20)
h1tev_at8tev_newiterVSvtxprobEB.Rebin2D(1,20)
h1tev_at8tev_newiterVSvtxprobBB.Rebin2D(1,20)

h1tev_at13tev_iterVSvtxprobBB_iterOld=h1tev_at13tev_iterVSvtxprobBB.Clone()
h1tev_at8tev_iterVSvtxprobBB_iterOld=h1tev_at8tev_iterVSvtxprobBB.Clone()
hprob_8tev_iterOldBB=h1tev_at8tev_iterVSvtxprobBB_iterOld.ProjectionY("hprob_8tev_iterOldBB",5,13)
hprob_13tev_iterOldBB=h1tev_at13tev_iterVSvtxprobBB_iterOld.ProjectionY("hprob_13tev_iterOldBB",5,13)

h1tev_at13tev_iterVSvtxprobBB_iterNew=h1tev_at13tev_newiterVSvtxprobBB.Clone()
h1tev_at8tev_iterVSvtxprobBB_iterNew=h1tev_at8tev_newiterVSvtxprobBB.Clone()
hprob_8tev_iterNewBB=h1tev_at8tev_iterVSvtxprobBB_iterNew.ProjectionY("hprob_8tev_iterNewBB",14,15)
hprob_13tev_iterNewBB=h1tev_at13tev_iterVSvtxprobBB_iterNew.ProjectionY("hprob_13tev_iterNewBB",14,15)

h1tev_at13tev_iterVSvtxprobEE_iterOld=h1tev_at13tev_iterVSvtxprobEE.Clone()
h1tev_at8tev_iterVSvtxprobEE_iterOld=h1tev_at8tev_iterVSvtxprobEE.Clone()
hprob_8tev_iterOldEE=h1tev_at8tev_iterVSvtxprobEE_iterOld.ProjectionY("hprob_8tev_iterOldEE",5,13)
hprob_13tev_iterOldEE=h1tev_at13tev_iterVSvtxprobEE_iterOld.ProjectionY("hprob_13tev_iterOldEE",5,13)

h1tev_at13tev_iterVSvtxprobEE_iterNew=h1tev_at13tev_newiterVSvtxprobEE.Clone()
h1tev_at8tev_iterVSvtxprobEE_iterNew=h1tev_at8tev_newiterVSvtxprobEE.Clone()
hprob_8tev_iterNewEE=h1tev_at8tev_iterVSvtxprobEE_iterNew.ProjectionY("hprob_8tev_iterNewEE",14,15)
hprob_13tev_iterNewEE=h1tev_at13tev_iterVSvtxprobEE_iterNew.ProjectionY("hprob_13tev_iterNewEE",14,15)

h1tev_at13tev_iterVSvtxprobEB_iterOld=h1tev_at13tev_iterVSvtxprobEB.Clone()
h1tev_at8tev_iterVSvtxprobEB_iterOld=h1tev_at8tev_iterVSvtxprobEB.Clone()
hprob_8tev_iterOldEB=h1tev_at8tev_iterVSvtxprobEB_iterOld.ProjectionY("hprob_8tev_iterOldEB",5,13)
hprob_13tev_iterOldEB=h1tev_at13tev_iterVSvtxprobEB_iterOld.ProjectionY("hprob_13tev_iterOldEB",5,13)

h1tev_at13tev_iterVSvtxprobEB_iterNew=h1tev_at13tev_newiterVSvtxprobEB.Clone()
h1tev_at8tev_iterVSvtxprobEB_iterNew=h1tev_at8tev_newiterVSvtxprobEB.Clone()
hprob_8tev_iterNewEB=h1tev_at8tev_iterVSvtxprobEB_iterNew.ProjectionY("hprob_8tev_iterNewEB",14,15)
hprob_13tev_iterNewEB=h1tev_at13tev_iterVSvtxprobEB_iterNew.ProjectionY("hprob_13tev_iterNewEB",14,15)

pad1.cd()
hprob_8tev_iterOldBB.Scale(1/hprob_8tev_iterOldBB.Integral())
hprob_13tev_iterOldBB.Scale(1/hprob_13tev_iterOldBB.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterOldBB.SetLineColor(1)
hprob_8tev_iterOldBB.SetLineWidth(2)
hprob_13tev_iterOldBB.SetLineColor(2)
hprob_13tev_iterOldBB.SetLineWidth(2)
hprob_13tev_iterOldBB.Draw("histo")
hprob_8tev_iterOldBB.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad2.cd()
hprob_13tev_iterNewBB.Scale(1/hprob_13tev_iterNewBB.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterNewBB.SetLineColor(1)
hprob_8tev_iterNewBB.SetLineWidth(2)
hprob_13tev_iterNewBB.SetLineColor(2)
hprob_13tev_iterNewBB.SetLineWidth(2)
hprob_13tev_iterNewBB.Draw("histo")
hprob_8tev_iterNewBB.Draw("histo same")
pad3.cd()
hprob_8tev_iterOldEE.Scale(1/hprob_8tev_iterOldEE.Integral())
hprob_13tev_iterOldEE.Scale(1/hprob_13tev_iterOldEE.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterOldEE.SetLineColor(1)
hprob_8tev_iterOldEE.SetLineWidth(2)
hprob_13tev_iterOldEE.SetLineColor(2)
hprob_13tev_iterOldEE.SetLineWidth(2)
hprob_13tev_iterOldEE.Draw("histo")
hprob_8tev_iterOldEE.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad4.cd()
#hprob_8tev_iterNewEE.Scale(1/hprob_8tev_iterNewEE.Integral())
hprob_13tev_iterNewEE.Scale(1/hprob_13tev_iterNewEE.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterNewEE.SetLineColor(1)
hprob_8tev_iterNewEE.SetLineWidth(2)
hprob_13tev_iterNewEE.SetLineColor(2)
hprob_13tev_iterNewEE.SetLineWidth(2)
hprob_13tev_iterNewEE.Draw("histo")
hprob_8tev_iterNewEE.Draw("histo same")
pad5.cd()
hprob_8tev_iterOldEB.Scale(1/hprob_8tev_iterOldEB.Integral())
hprob_13tev_iterOldEB.Scale(1/hprob_13tev_iterOldEB.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterOldEB.SetLineColor(1)
hprob_8tev_iterOldEB.SetLineWidth(2)
hprob_13tev_iterOldEB.SetLineColor(2)
hprob_13tev_iterOldEB.SetLineWidth(2)
hprob_13tev_iterOldEB.Draw("histo")
hprob_8tev_iterOldEB.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad6.cd()
#hprob_8tev_iterNewEE.Scale(1/hprob_8tev_iterNewEE.Integral())
hprob_13tev_iterNewEB.Scale(1/hprob_13tev_iterNewEB.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iterNewEB.SetLineColor(1)
hprob_8tev_iterNewEB.SetLineWidth(2)
hprob_13tev_iterNewEB.SetLineColor(2)
hprob_13tev_iterNewEB.SetLineWidth(2)
hprob_13tev_iterNewEB.Draw("histo")
hprob_8tev_iterNewEB.Draw("histo same")
c_scat.Print('DYsuperimposition_iterVSvtxprob.pdf')


c_scat = ROOT.TCanvas( 'c_scat', '')
pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
pad1.Draw()
pad2.Draw()
pad3.Draw()
pad4.Draw()
#h1tev_at8tev_iterVSprobB.Draw("colz")
h1tev_at8tev_iterVSprobB.Rebin2D(1,20)
h1tev_at13tev_iterVSprobB.Rebin2D(1,20)

#pad1.SetLogy()
h1tev_at13tev_iterVSprobB_iter0=h1tev_at13tev_iterVSprobB.Clone()
h1tev_at8tev_iterVSprobB_iter0=h1tev_at8tev_iterVSprobB.Clone()
hprob_8tev_iter0=h1tev_at8tev_iterVSprobB_iter0.ProjectionY("hprob_8tev_iter0",5,5)
hprob_13tev_iter0=h1tev_at13tev_iterVSprobB_iter0.ProjectionY("hprob_13tev_iter0",5,5)
h1tev_at13tev_iterVSprobB_iter2=h1tev_at13tev_iterVSprobB.Clone()
h1tev_at8tev_iterVSprobB_iter2=h1tev_at8tev_iterVSprobB.Clone()
hprob_8tev_iter2=h1tev_at8tev_iterVSprobB_iter2.ProjectionY("hprob_8tev_iter2",7,7)
hprob_13tev_iter2=h1tev_at13tev_iterVSprobB_iter2.ProjectionY("hprob_13tev_iter2",7,7)
h1tev_at13tev_iterVSprobB_iter9=h1tev_at13tev_iterVSprobB.Clone()
h1tev_at8tev_iterVSprobB_iter9=h1tev_at8tev_iterVSprobB.Clone()
hprob_8tev_iter9=h1tev_at8tev_iterVSprobB_iter9.ProjectionY("hprob_8tev_iter9",14,14)
hprob_13tev_iter9=h1tev_at13tev_iterVSprobB_iter9.ProjectionY("hprob_13tev_iter9",14,14)
h1tev_at13tev_iterVSprobB_iter10=h1tev_at13tev_iterVSprobB.Clone()
h1tev_at8tev_iterVSprobB_iter10=h1tev_at8tev_iterVSprobB.Clone()
hprob_8tev_iter10=h1tev_at8tev_iterVSprobB_iter10.ProjectionY("hprob_8tev_iter10",15,15)
hprob_13tev_iter10=h1tev_at13tev_iterVSprobB_iter10.ProjectionY("hprob_13tev_iter10",15,15)
pad1.cd()
hprob_8tev_iter0.Scale(1/hprob_8tev_iter0.Integral())
hprob_13tev_iter0.Scale(1/hprob_13tev_iter0.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iter0.SetLineColor(1)
hprob_8tev_iter0.SetLineWidth(2)
hprob_13tev_iter0.SetLineColor(2)
hprob_13tev_iter0.SetLineWidth(2)
hprob_13tev_iter0.Draw("histo")
hprob_8tev_iter0.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad2.cd()
hprob_8tev_iter2.Scale(1/hprob_8tev_iter2.Integral())
hprob_13tev_iter2.Scale(1/hprob_13tev_iter2.Integral())
hprob_8tev_iter2.SetLineColor(1)
hprob_8tev_iter2.SetLineWidth(2)
hprob_13tev_iter2.SetLineColor(2)
hprob_13tev_iter2.SetLineWidth(2)
hprob_13tev_iter2.Draw("histo")
hprob_8tev_iter2.Draw("histo same")
pad3.cd()
#hprob_8tev_iter9.Scale(1/hprob_8tev_iter9.Integral())
hprob_13tev_iter9.Scale(1/hprob_13tev_iter9.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iter9.SetLineColor(1)
hprob_8tev_iter9.SetLineWidth(2)
hprob_13tev_iter9.SetLineColor(2)
hprob_13tev_iter9.SetLineWidth(2)
hprob_13tev_iter9.Draw("histo")
hprob_8tev_iter9.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad4.cd()
#hprob_8tev_iter10.Scale(1/hprob_8tev_iter10.Integral())
hprob_13tev_iter10.Scale(1/hprob_13tev_iter10.Integral())
hprob_8tev_iter10.SetLineColor(1)
hprob_8tev_iter10.SetLineWidth(2)
hprob_13tev_iter10.SetLineColor(2)
hprob_13tev_iter10.SetLineWidth(2)
hprob_13tev_iter10.Draw("histo")
hprob_8tev_iter10.Draw("histo same")
c_scat.Print('DYsuperimposition_iterVSprobBarrel.pdf')

c_scat = ROOT.TCanvas( 'c_scat', '')
pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
pad1.Draw()
pad2.Draw()
pad3.Draw()
pad4.Draw()
#h1tev_at8tev_iterVSprobB.Draw("colz")
h1tev_at8tev_iterVSprobE.Rebin2D(1,20)
h1tev_at13tev_iterVSprobE.Rebin2D(1,20)

#pad1.SetLogy()
h1tev_at13tev_iterVSprobE_iter0=h1tev_at13tev_iterVSprobE.Clone()
h1tev_at8tev_iterVSprobE_iter0=h1tev_at8tev_iterVSprobE.Clone()
hprob_8tev_iter0E=h1tev_at8tev_iterVSprobE_iter0.ProjectionY("hprob_8tev_iter0E",5,5)
hprob_13tev_iter0E=h1tev_at13tev_iterVSprobE_iter0.ProjectionY("hprob_13tev_iter0E",5,5)
h1tev_at13tev_iterVSprobE_iter2=h1tev_at13tev_iterVSprobE.Clone()
h1tev_at8tev_iterVSprobE_iter2=h1tev_at8tev_iterVSprobE.Clone()
hprob_8tev_iter2E=h1tev_at8tev_iterVSprobE_iter2.ProjectionY("hprob_8tev_iter2E",7,7)
hprob_13tev_iter2E=h1tev_at13tev_iterVSprobE_iter2.ProjectionY("hprob_13tev_iter2E",7,7)
h1tev_at13tev_iterVSprobE_iter9=h1tev_at13tev_iterVSprobE.Clone()
h1tev_at8tev_iterVSprobE_iter9=h1tev_at8tev_iterVSprobE.Clone()
hprob_8tev_iter9E=h1tev_at8tev_iterVSprobE_iter9.ProjectionY("hprob_8tev_iter9E",14,14)
hprob_13tev_iter9E=h1tev_at13tev_iterVSprobE_iter9.ProjectionY("hprob_13tev_iter9E",14,14)
h1tev_at13tev_iterVSprobE_iter10=h1tev_at13tev_iterVSprobE.Clone()
h1tev_at8tev_iterVSprobE_iter10=h1tev_at8tev_iterVSprobE.Clone()
hprob_8tev_iter10E=h1tev_at8tev_iterVSprobE_iter10.ProjectionY("hprob_8tev_iter10E",15,15)
hprob_13tev_iter10E=h1tev_at13tev_iterVSprobE_iter10.ProjectionY("hprob_13tev_iter10E",15,15)
pad1.cd()
hprob_8tev_iter0E.Scale(1/hprob_8tev_iter0E.Integral())
hprob_13tev_iter0E.Scale(1/hprob_13tev_iter0E.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iter0E.SetLineColor(1)
hprob_8tev_iter0E.SetLineWidth(2)
hprob_13tev_iter0E.SetLineColor(2)
hprob_13tev_iter0E.SetLineWidth(2)
hprob_8tev_iter0E.Draw("histo")
hprob_13tev_iter0E.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad2.cd()
hprob_8tev_iter2E.Scale(1/hprob_8tev_iter2E.Integral())
hprob_13tev_iter2E.Scale(1/hprob_13tev_iter2E.Integral())
hprob_8tev_iter2E.SetLineColor(1)
hprob_8tev_iter2E.SetLineWidth(2)
hprob_13tev_iter2E.SetLineColor(2)
hprob_13tev_iter2E.SetLineWidth(2)
hprob_8tev_iter2E.Draw("histo")
hprob_13tev_iter2E.Draw("histo same")
pad3.cd()
#hprob_8tev_iter9E.Scale(1/hprob_8tev_iter9E.Integral())
hprob_13tev_iter9E.Scale(1/hprob_13tev_iter9E.Integral())
#hprob_8tev_iter0.Rebin(20)
#hprob_13tev_iter0.Rebin(20)
hprob_8tev_iter9E.SetLineColor(1)
hprob_8tev_iter9E.SetLineWidth(2)
hprob_13tev_iter9E.SetLineColor(2)
hprob_13tev_iter9E.SetLineWidth(2)
hprob_13tev_iter9E.Draw("histo")
hprob_8tev_iter9E.Draw("histo same")
#h1tev_at8tev_iterVSprobB_iter0.Draw("colz")
pad4.cd()
#hprob_8tev_iter10E.Scale(1/hprob_8tev_iter10E.Integral())
hprob_13tev_iter10E.Scale(1/hprob_13tev_iter10E.Integral())
hprob_8tev_iter10E.SetLineColor(1)
hprob_8tev_iter10E.SetLineWidth(2)
hprob_13tev_iter10E.SetLineColor(2)
hprob_13tev_iter10E.SetLineWidth(2)
hprob_13tev_iter10E.Draw("histo")
hprob_8tev_iter10E.Draw("histo same")
c_scat.Print('DYsuperimposition_iterVSprobEndcap.pdf')

#c_over = ROOT.TCanvas( 'c_over', '')
#c_over.SetLogy()
#h1tev_at8tev_chi.Rebin(5)
#h1tev_at13tev_chi.Rebin(5)
##h1tev_at8tev_chi.GetXaxis().SetRangeUser(0, 12)
##h1tev_at13tev_chi.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_chi_overf = PaintOverflow(h1tev_at8tev_chi)
#h1tev_at13tev_chi_overf = PaintOverflow(h1tev_at13tev_chi)
#h1tev_at8tev_chi_overf.Scale(1/h1tev_at8tev_chi_overf.Integral())
#h1tev_at13tev_chi_overf.Scale(1/h1tev_at13tev_chi_overf.Integral())
#h1tev_at8tev_chi_overf.SetLineColor(1)
#h1tev_at8tev_chi_overf.SetLineWidth(2)
#h1tev_at13tev_chi_overf.SetLineColor(2)
#h1tev_at13tev_chi_overf.SetLineWidth(2)
#h1tev_at8tev_chi_overf.Draw("histo")
##PaintOverflow(h1tev_at13tev_chi,"SAME HISTO")
#h1tev_at13tev_chi_overf.Draw("same histo")
#nx    = h1tev_at13tev_chi_overf.GetNbinsX()
#bw    = h1tev_at13tev_chi_overf.GetBinWidth(nx)
#x2    = h1tev_at13tev_chi_overf.GetBinLowEdge(nx)+bw
#t = ROOT.TText(x2-bw/2,h1tev_at13tev_chi_overf.GetBinContent(nx),"Overflow")
#t.SetTextAngle(90)
#t.SetTextAlign(12)
#t.SetTextSize(0.03)
#t.Draw("same")
#
#leg.Draw()
#c_over.Print('DYsuperimposition_overflow.pdf')
#
#c_eta = ROOT.TCanvas( 'c_eta', '')
##c_eta.Divide(2,1)
##c_eta.cd(1)
#h1tev_at8tev_LeptonEta.Scale(1/h1tev_at8tev_LeptonEta.Integral())
#h1tev_at13tev_LeptonEta.Scale(1/h1tev_at13tev_LeptonEta.Integral())
##h5tev_LeptonEta.Rebin(5)
##h1tev_at8tev_LeptonEta.Rebin(5)
##h1tev_at13tev_LeptonEta.Rebin(5)
#h1tev_at8tev_LeptonEta.SetLineColor(1)
#h1tev_at8tev_LeptonEta.SetLineWidth(2)
#h1tev_at13tev_LeptonEta.SetLineColor(2)
#h1tev_at13tev_LeptonEta.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h1tev_at8tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_LeptonEta.Draw("histo")
#h1tev_at13tev_LeptonEta.Draw("same histo")
##c_eta.cd(2)
##h1tev_at8tev_LeptonEta_MassRange.Scale(1/h1tev_at8tev_LeptonEta_MassRange.Integral())
##h1tev_at13tev_LeptonEta_MassRange.Scale(1/h1tev_at13tev_LeptonEta_MassRange.Integral())
###h5tev_LeptonEta.Rebin(5)
###h1tev_at8tev_LeptonEta.Rebin(5)
###h1tev_at13tev_LeptonEta.Rebin(5)
##h1tev_at8tev_LeptonEta_MassRange.SetLineColor(1)
##h1tev_at8tev_LeptonEta_MassRange.SetLineWidth(2)
##h1tev_at13tev_LeptonEta_MassRange.SetLineColor(3)
##h1tev_at13tev_LeptonEta_MassRange.SetLineWidth(2)
###h5tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h1tev_at8tev_LeptonEta_MassRange.GetYaxis().SetRangeUser(0, 0.04)
###h5tev_prob.GetYaxis().SetLog()
##h1tev_at8tev_LeptonEta_MassRange.Draw("histo")
##h1tev_at13tev_LeptonEta_MassRange.Draw("same histo")
#
#leg.Draw()
#c_eta.Print('DYsuperimposition_eta.pdf')
#
#c_vtxprob = ROOT.TCanvas( 'c_vtxprob', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
#pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
#pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
#pad1.Draw()
#pad2.Draw()
#pad3.Draw()
#pad4.Draw()
#pad1.cd()
##pad1.SetLogy()
#h1tev_at8tev_prob_BB.Scale(1/h1tev_at8tev_prob_BB.Integral())
#h1tev_at13tev_prob_BB.Scale(1/h1tev_at13tev_prob_BB.Integral())
#h1tev_at8tev_prob_BB.Rebin(20)
#h1tev_at13tev_prob_BB.Rebin(20)
#h1tev_at8tev_prob_BB.SetLineColor(1)
#h1tev_at8tev_prob_BB.SetLineWidth(2)
#h1tev_at13tev_prob_BB.SetLineColor(2)
#h1tev_at13tev_prob_BB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at13tev_prob_BB.Draw("histo")
#h1tev_at8tev_prob_BB.Draw("same histo")
#pad2.cd()
##pad2.SetLogy()
#h1tev_at8tev_prob_EE.Scale(1/h1tev_at8tev_prob_EE.Integral())
#h1tev_at13tev_prob_EE.Scale(1/h1tev_at13tev_prob_EE.Integral())
#h1tev_at8tev_prob_EE.Rebin(20)
#h1tev_at13tev_prob_EE.Rebin(20)
#h1tev_at8tev_prob_EE.SetLineColor(1)
#h1tev_at8tev_prob_EE.SetLineWidth(2)
#h1tev_at13tev_prob_EE.SetLineColor(2)
#h1tev_at13tev_prob_EE.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at13tev_prob_EE.Draw("histo")
#h1tev_at8tev_prob_EE.Draw("same histo")
#leg.Draw()
#pad3.cd()
##pad3.SetLogy()
#h1tev_at8tev_prob_EB.Scale(1/h1tev_at8tev_prob_EB.Integral())
#h1tev_at13tev_prob_EB.Scale(1/h1tev_at13tev_prob_EB.Integral())
#h1tev_at8tev_prob_EB.Rebin(20)
#h1tev_at13tev_prob_EB.Rebin(20)
#h1tev_at8tev_prob_EB.SetLineColor(1)
#h1tev_at8tev_prob_EB.SetLineWidth(2)
#h1tev_at13tev_prob_EB.SetLineColor(2)
#h1tev_at13tev_prob_EB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at13tev_prob_EB.Draw("histo")
#h1tev_at8tev_prob_EB.Draw("same histo")
#leg.Draw()
#c_vtxprob.Print('DYsuperimposition_vtxprob_noLog.pdf')
#
#c_trkprob = ROOT.TCanvas( 'c_trkprob', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
##pad1.SetLogy()
#h1tev_at8tev_MuonProbB.Scale(1/h1tev_at8tev_MuonProbB.Integral())
#h1tev_at13tev_MuonProbB.Scale(1/h1tev_at13tev_MuonProbB.Integral())
#h1tev_at8tev_MuonProbB.Rebin(20)
#h1tev_at13tev_MuonProbB.Rebin(20)
#h1tev_at8tev_MuonProbB.SetLineColor(1)
#h1tev_at8tev_MuonProbB.SetLineWidth(2)
#h1tev_at13tev_MuonProbB.SetLineColor(2)
#h1tev_at13tev_MuonProbB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at13tev_MuonProbB.Draw("histo")
#h1tev_at8tev_MuonProbB.Draw("same histo")
#leg.Draw()
#pad2.cd()
##pad2.SetLogy()
#h1tev_at8tev_MuonProbE.Scale(1/h1tev_at8tev_MuonProbE.Integral())
#h1tev_at13tev_MuonProbE.Scale(1/h1tev_at13tev_MuonProbE.Integral())
#h1tev_at8tev_MuonProbE.Rebin(20)
#h1tev_at13tev_MuonProbE.Rebin(20)
#h1tev_at8tev_MuonProbE.SetLineColor(1)
#h1tev_at8tev_MuonProbE.SetLineWidth(2)
#h1tev_at13tev_MuonProbE.SetLineColor(2)
#h1tev_at13tev_MuonProbE.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_MuonProbE.Draw("histo")
#h1tev_at13tev_MuonProbE.Draw("same histo")
#leg.Draw()
#
#c_trkprob.Print('DYsuperimposition_trkprob_noLog.pdf')

#c_pterr_m = ROOT.TCanvas( 'c_pterr_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h1tev_at8tev_MuonPtErrorB_overf = PaintOverflow(h1tev_at8tev_MuonPtErrorB)
#h1tev_at13tev_MuonPtErrorB_overf = PaintOverflow(h1tev_at13tev_MuonPtErrorB)
#h1tev_at8tev_MuonPtErrorB_overf.Scale(1/h1tev_at8tev_MuonPtErrorB_overf.Integral())
#h1tev_at13tev_MuonPtErrorB_overf.Scale(1/h1tev_at13tev_MuonPtErrorB_overf.Integral())
#h1tev_at8tev_MuonPtErrorB_overf.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorB_overf.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorB_overf.SetLineColor(2)
#h1tev_at13tev_MuonPtErrorB_overf.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorB_overf.Draw("histo")
#h1tev_at13tev_MuonPtErrorB_overf.Draw("same histo")
#leg.Draw()
#nx    = h1tev_at13tev_MuonPtErrorB_overf.GetNbinsX()
#bw    = h1tev_at13tev_MuonPtErrorB_overf.GetBinWidth(nx)
#x2    = h1tev_at13tev_MuonPtErrorB_overf.GetBinLowEdge(nx)+bw
#t = ROOT.TText(x2-bw/2,h1tev_at13tev_MuonPtErrorB_overf.GetBinContent(nx),"Overflow")
#t.SetTextAngle(90)
#t.SetTextAlign(12)
#t.SetTextSize(0.03)
#t.Draw("same")
#pad2.cd()
#pad2.SetLogy()
#h1tev_at8tev_MuonPtErrorE_overf = PaintOverflow(h1tev_at8tev_MuonPtErrorE)
#h1tev_at13tev_MuonPtErrorE_overf = PaintOverflow(h1tev_at13tev_MuonPtErrorE)
#h1tev_at8tev_MuonPtErrorE_overf.Scale(1/h1tev_at8tev_MuonPtErrorE_overf.Integral())
#h1tev_at13tev_MuonPtErrorE_overf.Scale(1/h1tev_at13tev_MuonPtErrorE_overf.Integral())
#h1tev_at8tev_MuonPtErrorE_overf.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorE_overf.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorE_overf.SetLineColor(2)
#h1tev_at13tev_MuonPtErrorE_overf.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorE_overf.Draw("histo")
#h1tev_at13tev_MuonPtErrorE_overf.Draw("same histo")
#leg.Draw()
#nx    = h1tev_at13tev_MuonPtErrorE_overf.GetNbinsX()
#bw    = h1tev_at13tev_MuonPtErrorE_overf.GetBinWidth(nx)
#x2    = h1tev_at13tev_MuonPtErrorE_overf.GetBinLowEdge(nx)+bw
#t = ROOT.TText(x2-bw/2,h1tev_at13tev_MuonPtErrorE_overf.GetBinContent(nx),"Overflow")
#t.SetTextAngle(90)
#t.SetTextAlign(12)
#t.SetTextSize(0.03)
#t.Draw("same")
#c_pterr_m.Print('DYsuperimposition_pterr.pdf')


#c_pterrOver_m = ROOT.TCanvas( 'c_pterrOver_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Integral())
##h5tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorB_MassRange.Rebin(10)
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.SetLineColor(2)
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.GetXaxis().SetRangeUser(0, 0.5 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Draw("histo")
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Draw("same histo")
#leg.Draw()
#pad2.cd()
#pad2.SetLogy()
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Integral())
##h5tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.SetLineColor(2)
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.GetXaxis().SetRangeUser(0, 0.5 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Draw("histo")
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Draw("same histo")
#leg.Draw()
#
#c_pterrOver_m.Print('DYsuperimposition_pterrOverpt.pdf')


#c_d0 = ROOT.TCanvas( 'c_d0', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
##pad1.SetLogy()
#h1tev_at8tev_d0B.Scale(1/h1tev_at8tev_d0B.Integral())
#h1tev_at13tev_d0B.Scale(1/h1tev_at13tev_d0B.Integral())
##h1tev_at8tev_d0B.Rebin(20)
##h1tev_at13tev_d0B.Rebin(20)
#h1tev_at8tev_d0B.SetLineColor(1)
#h1tev_at8tev_d0B.SetLineWidth(2)
#h1tev_at13tev_d0B.SetLineColor(2)
#h1tev_at13tev_d0B.SetLineWidth(2)
#h1tev_at8tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at13tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_d0B.Draw("histo")
#h1tev_at13tev_d0B.Draw("same histo")
#leg.Draw()
#pad2.cd()
##pad2.SetLogy()
#h1tev_at8tev_d0E.Scale(1/h1tev_at8tev_d0E.Integral())
#h1tev_at13tev_d0E.Scale(1/h1tev_at13tev_d0E.Integral())
##h1tev_at8tev_d0E.Rebin(20)
##h1tev_at13tev_d0E.Rebin(20)
#h1tev_at8tev_d0E.SetLineColor(1)
#h1tev_at8tev_d0E.SetLineWidth(2)
#h1tev_at13tev_d0E.SetLineColor(2)
#h1tev_at13tev_d0E.SetLineWidth(2)
#h1tev_at13tev_d0E.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at8tev_d0E.GetXaxis().SetRangeUser(0, 0.02)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h1tev_at8tev_d0E.Draw("histo")
#h1tev_at13tev_d0E.Draw("same histo")
#leg.Draw()
#c_d0.Print('DYsuperimposition_d0BS.pdf')

c_iter = ROOT.TCanvas( 'c_iter', '')
pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
pad1.Draw()
pad2.Draw()

pad1.cd()
#pad1.SetLogy()
h1tev_at8tev_iterB.Scale(1/h1tev_at8tev_iterB.Integral())
h1tev_at13tev_iterB.Scale(1/h1tev_at13tev_iterB.Integral())
#h1tev_at8tev_d0B.Rebin(20)
#h1tev_at13tev_d0B.Rebin(20)
h1tev_at8tev_iterB.SetLineColor(1)
h1tev_at8tev_iterB.SetLineWidth(2)
h1tev_at13tev_iterB.SetLineColor(2)
h1tev_at13tev_iterB.SetLineWidth(2)
#h1tev_at8tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at13tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
#h5tev_prob.GetYaxis().SetLog()
h1tev_at8tev_iterB.Draw("histo")
h1tev_at13tev_iterB.Draw("same histo")
leg.Draw()
pad2.cd()
#pad2.SetLogy()
h1tev_at8tev_iterE.Scale(1/h1tev_at8tev_iterE.Integral())
h1tev_at13tev_iterE.Scale(1/h1tev_at13tev_iterE.Integral())
#h1tev_at8tev_d0B.Rebin(20)
#h1tev_at13tev_d0B.Rebin(20)
h1tev_at8tev_iterE.SetLineColor(1)
h1tev_at8tev_iterE.SetLineWidth(2)
h1tev_at13tev_iterE.SetLineColor(2)
h1tev_at13tev_iterE.SetLineWidth(2)
#h1tev_at8tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at13tev_d0B.GetXaxis().SetRangeUser(0, 0.02)
#h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
#h5tev_prob.GetYaxis().SetLog()
h1tev_at8tev_iterE.Draw("histo")
h1tev_at13tev_iterE.Draw("same histo")
leg.Draw()
c_iter.Print('DYsuperimposition_iter.pdf')


c = ROOT.TCanvas( 'c', '')
#c.Divide(1,2)
#c.SetLogy()
pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
pad1.Draw()
pad2.Draw()
pad3.Draw()
pad4.Draw()

pad1.cd()
#pad1.SetLogy()
h1tev_at8tev.Scale(1/h1tev_at8tev.Integral())
h1tev_at13tev.Scale(1/h1tev_at13tev.Integral())
#h5tev.Rebin(10)
#h1tev_at8tev.Rebin(10)
#h1tev_at13tev.Rebin(10)

h1tev_at8tev.SetLineColor(1)
h1tev_at8tev.SetLineWidth(2)
h1tev_at13tev.SetLineColor(2)
h1tev_at13tev.SetLineWidth(2)

h1tev_at8tev.GetYaxis().SetRangeUser(0, 0.24)
#h1tev_at13tev.GetYaxis().SetRangeUser(0, 0.08)
h1tev_at8tev.GetXaxis().SetRangeUser(0, 4000)
h1tev_at13tev.GetXaxis().SetRangeUser(0, 4000)
h1tev_at8tev.Draw("histo")
h1tev_at13tev.Draw("same histo")
                  #h5tev.Fit('gaus', '','',-0.1,0.1)
leg.Draw()
####################

pad2.cd()
#pad2.SetLogy()
#p1->SetLogx();

#h5tev_Nvtx.Scale(1/h5tev_Nvtx.Integral())
#h1tev_at8tev_Nvtx.Scale(1/h1tev_at8tev_Nvtx.Integral())
#h1tev_at13tev_Nvtx.Scale(1/h1tev_at13tev_Nvtx.Integral())
#h5tev_Nvtx.Rebin(5)
#h1tev_at8tev_Nvtx.Rebin(5)
#h1tev_at13tev_Nvtx.Rebin(5)
#h5tev_Nvtx.SetLineColor(6)
#h5tev_Nvtx.SetLineWidth(2)
#h1tev_at8tev_Nvtx.SetLineColor(1)
#h1tev_at8tev_Nvtx.SetLineWidth(2)
#h1tev_at13tev_Nvtx.SetLineColor(3)
#h1tev_at13tev_Nvtx.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_Nvtx.GetYaxis().SetRangeUser(0, 0.5)
##h5tev_prob.GetYaxis().SetLog()
#h5tev_Nvtx.Draw("HISTO")
#h1tev_at8tev_Nvtx.Draw("same histo")
#h1tev_at13tev_Nvtx.Draw("same histo")
#c.SetLogy();
h1tev_at8tev_LeptonEta.Scale(1/h1tev_at8tev_LeptonEta.Integral())
h1tev_at13tev_LeptonEta.Scale(1/h1tev_at13tev_LeptonEta.Integral())
#h5tev_LeptonEta.Rebin(5)
#h1tev_at8tev_LeptonEta.Rebin(5)
#h1tev_at13tev_LeptonEta.Rebin(5)
h1tev_at8tev_LeptonEta.SetLineColor(1)
h1tev_at8tev_LeptonEta.SetLineWidth(2)
h1tev_at13tev_LeptonEta.SetLineColor(2)
h1tev_at13tev_LeptonEta.SetLineWidth(2)
#h5tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.5)
#h5tev_prob.GetYaxis().SetLog()
h1tev_at8tev_LeptonEta.Draw("histo")
h1tev_at13tev_LeptonEta.Draw("same histo")


leg.Draw()

#########################

pad4.cd()
pad4.SetLogy()
#p1->SetLogx();

h1tev_at8tev_MuonProb.Scale(1/h1tev_at8tev_MuonProb.Integral())
h1tev_at13tev_MuonProb.Scale(1/h1tev_at13tev_MuonProb.Integral())
h1tev_at8tev_MuonProb.Rebin(20)
h1tev_at13tev_MuonProb.Rebin(20)

h1tev_at8tev_MuonProb.SetLineColor(1)
h1tev_at8tev_MuonProb.SetLineWidth(2)
h1tev_at13tev_MuonProb.SetLineColor(2)
h1tev_at13tev_MuonProb.SetLineWidth(2)
#h5tev_MuonProb.GetYaxis().SetRangeUser(0, 0.085)
h1tev_at8tev_MuonProb.Draw("histo")
h1tev_at13tev_MuonProb.Draw("same histo")
#########################

pad3.cd()
pad3.SetLogy()
#p1->SetLogx();

h1tev_at8tev_prob.Scale(1/h1tev_at8tev_prob.Integral())
h1tev_at13tev_prob.Scale(1/h1tev_at13tev_prob.Integral())
h1tev_at8tev_prob.Rebin(20)
h1tev_at13tev_prob.Rebin(20)
h1tev_at8tev_prob.SetLineColor(1)
h1tev_at8tev_prob.SetLineWidth(2)
h1tev_at13tev_prob.SetLineColor(2)
h1tev_at13tev_prob.SetLineWidth(2)
#h5tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_prob.GetYaxis().SetLog()
h1tev_at8tev_prob.Draw("histo")
h1tev_at13tev_prob.Draw("same histo")
#c.SetLogy();

leg.Draw()
###################################
#pad3.cd()
#pad3.SetLogy()
##p1->SetLogx();
#
#h5tev_chi.Scale(1/h5tev_chi.Integral())
#h1tev_at8tev_chi.Scale(1/h1tev_at8tev_chi.Integral())
#h1tev_at13tev_chi.Scale(1/h1tev_at13tev_chi.Integral())
#h5tev_chi.Rebin(5)
#h1tev_at8tev_chi.Rebin(5)
#h1tev_at13tev_chi.Rebin(5)
#h5tev_chi.SetLineColor(6)
#h5tev_chi.SetLineWidth(2)
#h1tev_at8tev_chi.SetLineColor(1)
#h1tev_at8tev_chi.SetLineWidth(2)
#h1tev_at13tev_chi.SetLineColor(3)
#h1tev_at13tev_chi.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_prob.GetYaxis().SetLog()
#h5tev_chi.Draw("HISTO")
#h1tev_at8tev_chi.Draw("same histo")
#h1tev_at13tev_chi.Draw("same histo")
#c.SetLogy();

leg.Draw()

c.Print('DYsuperimposition_zprime.pdf')
#
#
#c2 = ROOT.TCanvas( 'c2', '')
##c.Divide(1,2)
##c.SetLogy()
#pad11 = TPad( 'pad11', '', 0.03, 0.50, 0.48, 0.95)
#pad22 = TPad( 'pad22', '', 0.50, 0.50, 0.98, 0.95)
#pad33 = TPad( 'pad33', '', 0.03, 0.02, 0.48, 0.48)
#pad44 = TPad( 'pad44', '', 0.50, 0.02, 0.98, 0.48)
#pad11.Draw()
#pad22.Draw()
#pad33.Draw()
#pad44.Draw()
#
#pad11.cd()
#pad11.SetLogy()
#h5tev_MuonProb.Scale(1/h5tev_MuonProb.Integral())
#h1tev_at8tev_MuonProb.Scale(1/h1tev_at8tev_MuonProb.Integral())
#h1tev_at13tev_MuonProb.Scale(1/h1tev_at13tev_MuonProb.Integral())
##h5tev_MuonProb.Rebin(10)
##h1tev_at8tev_MuonProb.Rebin(10)
##h1tev_at13tev_MuonProb.Rebin(10)
#
#h5tev_MuonProb.SetLineColor(6)
#h5tev_MuonProb.SetLineWidth(2)
#h1tev_at8tev_MuonProb.SetLineColor(1)
#h1tev_at8tev_MuonProb.SetLineWidth(2)
#h1tev_at13tev_MuonProb.SetLineColor(3)
#h1tev_at13tev_MuonProb.SetLineWidth(2)
##h5tev_MuonProb.GetYaxis().SetRangeUser(0, 0.085)
#h5tev_MuonProb.Draw("HISTO")
#h1tev_at8tev_MuonProb.Draw("same histo")
#h1tev_at13tev_MuonProb.Draw("same histo")
##h5tev.Fit('gaus', '','',-0.1,0.1)
#leg.Draw()
#
#pad22.cd()
#pad22.SetLogy()
#h5tev_MuonPtErrOverPt.Scale(1/h5tev_MuonPtErrOverPt.Integral())
#h1tev_at8tev_MuonPtErrOverPt.Scale(1/h1tev_at8tev_MuonPtErrOverPt.Integral())
#h1tev_at13tev_MuonPtErrOverPt.Scale(1/h1tev_at13tev_MuonPtErrOverPt.Integral())
##h5tev_MuonPtErrOverPt.Rebin(10)
##h1tev_at8tev_MuonPtErrOverPt.Rebin(10)
## h1tev_at13tev_MuonPtErrOverPt.Rebin(10)
#
#h5tev_MuonPtErrOverPt.SetLineColor(6)
#h5tev_MuonPtErrOverPt.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrOverPt.SetLineColor(1)
#h1tev_at8tev_MuonPtErrOverPt.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrOverPt.SetLineColor(3)
#h1tev_at13tev_MuonPtErrOverPt.SetLineWidth(2)
#h5tev_MuonPtErrOverPt.GetXaxis().SetRangeUser(0, 0.5)
#h5tev_MuonPtErrOverPt.Draw("HISTO")
#h1tev_at8tev_MuonPtErrOverPt.Draw("same histo")
#h1tev_at13tev_MuonPtErrOverPt.Draw("same histo")
##h5tev.Fit('gaus', '','',-0.1,0.1)
#leg.Draw()
#
#c2.Print('DYsuperimposition2_zprime.pdf')

###ps = plot_saver('plots/resfromdy_new')

