#!/usr/bin/env python

# (py resfromdy.py >! plots/out.resfromdy) && tlp plots/*resfromdy

import os
import ROOT
import math
from array import array
from ROOT import *
#from SUSYBSMAnalysis.Zprime2muAnalysis.roottools import *
#set_zp2mu_style()
#ROOT.gStyle.SetOptFit(1111)
gStyle.SetOptStat("")

ROOT.gStyle.SetPadTopMargin(0.02)
ROOT.gStyle.SetPadRightMargin(0.02)

def PaintOverflow(h, opt=''):
    #This function paint the histogram h with an extra bin for overflows
    name  = h.GetName()
    print name
    title = h.GetTitle()
    nx    = h.GetNbinsX()+1
    x1    = h.GetBinLowEdge(1)
    bw    = h.GetBinWidth(nx)
    x2    = h.GetBinLowEdge(nx)+bw
    #print nx, x1, bw, x2
    htmp  = ROOT.TH1F(name, title, nx, x1, x2)
    for i in xrange(1, nx+1):
        htmp.Fill(htmp.GetBinCenter(i), h.GetBinContent(i))
        #print i, h.GetBinContent(i)
    htmp.Fill(x1-1, h.GetBinContent(0))
    htmp.SetEntries(h.GetEntries())
    return htmp
#    c_tmp = ROOT.TCanvas( 'c_tmp', '')
#    htmp.Draw(opt)
#    t = ROOT.TText(x2-bw/2,h.GetBinContent(nx),"Overflow")
#    t.SetTextAngle(90)
#    t.SetTextAlign(12)
#    t.SetTextSize(0.03)
#    t.Draw("same")
#    c_tmp.Print('tmp.pdf')


f5tev = ROOT.TFile('./files/zp2mu_5000_13.root')
d5tev = f5tev.HistosVertexFromPAT
h5tev = d5tev.Get('DimuonMassVertexConstrained')
h5tev_LeptonEta = d5tev.Get('DimuonMassVtx_LeptonEta')
h5tev_LeptonEta_MassRange = d5tev.Get('DimuonMassVtx_LeptonEta_MassRange')
h5tev_Nvtx = d5tev.Get('NVertices')

h5tev_chi = d5tev.Get('DimuonMassVtx_chi2')
h5tev_prob = d5tev.Get('DimuonMassVtx_prob')
h5tev_MuonProb = d5tev.Get('DimuonMuonPtProb')
h5tev_MuonPtErrOverPt = d5tev.Get('DimuonMuonPtErrOverPt')

h5tev_MuonProbB = d5tev.Get('DimuonMuonPtProb_Barrel')
h5tev_MuonProbE = d5tev.Get('DimuonMuonPtProb_Endcap')
h5tev_MuonProbB_MassRange = d5tev.Get('DimuonMuonPtProb_Barrel_MassRange')
h5tev_MuonProbE_MassRange = d5tev.Get('DimuonMuonPtProb_Endcap_MassRange')

h5tev_MuonPtErrorB_MassRange = d5tev.Get('DimuonMuonPtError_Barrel_MassRange')
h5tev_MuonPtErrorE_MassRange = d5tev.Get('DimuonMuonPtError_Endcap_MassRange')
h5tev_MuonPtErrorOverPtB_MassRange = d5tev.Get('DimuonMuonPtErrOverPt_Barrel_MassRange')
h5tev_MuonPtErrorOverPtE_MassRange = d5tev.Get('DimuonMuonPtErrOverPt_Endcap_MassRange')

h5tev_prob_BB = d5tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h5tev_prob_EE = d5tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h5tev_prob_EB = d5tev.Get('DimuonMassVtx_prob_EndcapBarrel')
h5tev_prob_BB_MassRange = d5tev.Get('DimuonMassVtx_prob_BarrelBarrel_MassRange')
h5tev_prob_EE_MassRange = d5tev.Get('DimuonMassVtx_prob_EndcapEndcap_MassRange')
h5tev_prob_EB_MassRange = d5tev.Get('DimuonMassVtx_prob_EndcapBarrel_MassRange')

################

f1tev_at8tev = ROOT.TFile('./files/zp2mu_1000_8.root')
d1tev_at8tev = f1tev_at8tev.HistosVertexFromPAT
h1tev_at8tev = d1tev_at8tev.Get('DimuonMassVertexConstrained')
h1tev_at8tev_LeptonEta = d1tev_at8tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at8tev_LeptonEta_MassRange = d1tev_at8tev.Get('DimuonMassVtx_LeptonEta_MassRange')
h1tev_at8tev_Nvtx = d1tev_at8tev.Get('NVertices')

h1tev_at8tev_chi = d1tev_at8tev.Get('DimuonMassVtx_chi2')
h1tev_at8tev_prob = d1tev_at8tev.Get('DimuonMassVtx_prob')
h1tev_at8tev_MuonProb = d1tev_at8tev.Get('DimuonMuonPtProb')
h1tev_at8tev_MuonPtErrOverPt = d1tev_at8tev.Get('DimuonMuonPtErrOverPt')

h1tev_at8tev_MuonProbB = d1tev_at8tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at8tev_MuonProbE = d1tev_at8tev.Get('DimuonMuonPtProb_Endcap')
h1tev_at8tev_MuonProbB_MassRange = d1tev_at8tev.Get('DimuonMuonPtProb_Barrel_MassRange')
h1tev_at8tev_MuonProbE_MassRange = d1tev_at8tev.Get('DimuonMuonPtProb_Endcap_MassRange')

h1tev_at8tev_MuonPtErrorB_MassRange = d1tev_at8tev.Get('DimuonMuonPtError_Barrel_MassRange')
h1tev_at8tev_MuonPtErrorE_MassRange = d1tev_at8tev.Get('DimuonMuonPtError_Endcap_MassRange')
h1tev_at8tev_MuonPtErrorOverPtB_MassRange = d1tev_at8tev.Get('DimuonMuonPtErrOverPt_Barrel_MassRange')
h1tev_at8tev_MuonPtErrorOverPtE_MassRange = d1tev_at8tev.Get('DimuonMuonPtErrOverPt_Endcap_MassRange')

h1tev_at8tev_prob_BB = d1tev_at8tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at8tev_prob_EE = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at8tev_prob_EB = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapBarrel')
h1tev_at8tev_prob_BB_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_BarrelBarrel_MassRange')
h1tev_at8tev_prob_EE_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapEndcap_MassRange')
h1tev_at8tev_prob_EB_MassRange = d1tev_at8tev.Get('DimuonMassVtx_prob_EndcapBarrel_MassRange')

##################

f1tev_at13tev = ROOT.TFile('./files/zp2mu_1000_13.root')
d1tev_at13tev = f1tev_at13tev.HistosVertexFromPAT
h1tev_at13tev = d1tev_at13tev.Get('DimuonMassVertexConstrained')
h1tev_at13tev_LeptonEta = d1tev_at13tev.Get('DimuonMassVtx_LeptonEta')
h1tev_at13tev_LeptonEta_MassRange = d1tev_at13tev.Get('DimuonMassVtx_LeptonEta_MassRange')
h1tev_at13tev_Nvtx = d1tev_at13tev.Get('NVertices')

h1tev_at13tev_chi = d1tev_at13tev.Get('DimuonMassVtx_chi2')
h1tev_at13tev_prob = d1tev_at13tev.Get('DimuonMassVtx_prob')
h1tev_at13tev_MuonProb = d1tev_at13tev.Get('DimuonMuonPtProb')
h1tev_at13tev_MuonPtErrOverPt = d1tev_at13tev.Get('DimuonMuonPtErrOverPt')

h1tev_at13tev_MuonProbB = d1tev_at13tev.Get('DimuonMuonPtProb_Barrel')
h1tev_at13tev_MuonProbE = d1tev_at13tev.Get('DimuonMuonPtProb_Endcap')
h1tev_at13tev_MuonProbB_MassRange = d1tev_at13tev.Get('DimuonMuonPtProb_Barrel_MassRange')
h1tev_at13tev_MuonProbE_MassRange = d1tev_at13tev.Get('DimuonMuonPtProb_Endcap_MassRange')

h1tev_at13tev_MuonPtErrorB_MassRange = d1tev_at13tev.Get('DimuonMuonPtError_Barrel_MassRange')
h1tev_at13tev_MuonPtErrorE_MassRange = d1tev_at13tev.Get('DimuonMuonPtError_Endcap_MassRange')
h1tev_at13tev_MuonPtErrorOverPtB_MassRange = d1tev_at13tev.Get('DimuonMuonPtErrOverPt_Barrel_MassRange')
h1tev_at13tev_MuonPtErrorOverPtE_MassRange = d1tev_at13tev.Get('DimuonMuonPtErrOverPt_Endcap_MassRange')

h1tev_at13tev_prob_BB = d1tev_at13tev.Get('DimuonMassVtx_prob_BarrelBarrel')
h1tev_at13tev_prob_EE = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapEndcap')
h1tev_at13tev_prob_EB = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapBarrel')
h1tev_at13tev_prob_BB_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_BarrelBarrel_MassRange')
h1tev_at13tev_prob_EE_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapEndcap_MassRange')
h1tev_at13tev_prob_EB_MassRange = d1tev_at13tev.Get('DimuonMassVtx_prob_EndcapBarrel_MassRange')

#h5tev = fit_gaussian(h5tev,None,True)
#h5tev = fit_gaussian(h5tev,None,True)

# Legend:
leg = ROOT.TLegend( 0.65, 0.75, 0.9, 0.9 )
leg.SetFillColor(kWhite)
leg.SetLineColor(kWhite)
leg.SetTextSize(0.03)
leg.AddEntry(h1tev_at8tev, " Z' 1TeV @ 8TeV", "L")
leg.AddEntry(h1tev_at13tev, " Z' 1TeV @ 13TeV (cmssw 701)", "L")
leg.AddEntry(h5tev, " Z' 5TeV @ 13TeV (phys14)", "L")

c_mass = ROOT.TCanvas( 'c_mass', '')
h5tev.Scale(1/h5tev.Integral())
h1tev_at8tev.Scale(1/h1tev_at8tev.Integral())
h1tev_at13tev.Scale(1/h1tev_at13tev.Integral())
#h5tev.Rebin(10)
#h1tev_at8tev.Rebin(10)
#h1tev_at13tev.Rebin(10)

h5tev.SetLineColor(6)
h5tev.SetLineWidth(2)
h1tev_at8tev.SetLineColor(1)
h1tev_at8tev.SetLineWidth(2)
h1tev_at13tev.SetLineColor(3)
h1tev_at13tev.SetLineWidth(2)

h1tev_at8tev.GetYaxis().SetRangeUser(0, 0.085)
h1tev_at13tev.GetYaxis().SetRangeUser(0, 0.085)
h5tev.GetYaxis().SetRangeUser(0, 0.085)
h5tev.GetXaxis().SetRangeUser(0, 6200)
h1tev_at8tev.GetXaxis().SetRangeUser(0, 6000)
h1tev_at13tev.GetXaxis().SetRangeUser(0, 6000)
h5tev.Draw("HISTO")
h1tev_at8tev.Draw("same histo")
h1tev_at13tev.Draw("same histo")
leg.Draw()
c_mass.Print('superimposition_mass.pdf')


c_over = ROOT.TCanvas( 'c_over', '')
c_over.SetLogy()
#print h5tev_chi.GetNbinsX()
h5tev_chi.Rebin(100)
h1tev_at8tev_chi.Rebin(100)
h1tev_at13tev_chi.Rebin(100)
h5tev_chi_overf = PaintOverflow(h5tev_chi).Clone()
h1tev_at8tev_chi_overf = PaintOverflow(h1tev_at8tev_chi).Clone()
h1tev_at13tev_chi_overf = PaintOverflow(h1tev_at13tev_chi).Clone()
#print h5tev_chi_overf.GetNbinsX(), "overflow", h5tev_chi_overf.GetBinContent(h5tev_chi_overf.GetNbinsX()+1)

#h5tev_chi_overf.Scale(1/h5tev_chi_overf.Integral())
#h1tev_at8tev_chi_overf.Scale(1/h1tev_at8tev_chi_overf.Integral())
#h1tev_at13tev_chi_overf.Scale(1/h1tev_at13tev_chi_overf.Integral())
h5tev_chi_overf.SetLineColor(6)
h5tev_chi_overf.SetLineWidth(2)
h1tev_at8tev_chi_overf.SetLineColor(1)
h1tev_at8tev_chi_overf.SetLineWidth(2)
h1tev_at13tev_chi_overf.SetLineColor(3)
h1tev_at13tev_chi_overf.SetLineWidth(2)
h5tev_chi_overf.SetMinimum(1)
#h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
#h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_prob.GetYaxis().SetLog()
h5tev_chi_overf.Draw("HISTO")
h1tev_at8tev_chi_overf.Draw("same histo")
h1tev_at13tev_chi_overf.Draw("same histo")
nx    = h1tev_at8tev_chi_overf.GetNbinsX()
bw    = h1tev_at8tev_chi_overf.GetBinWidth(nx)
x2    = h1tev_at8tev_chi_overf.GetBinLowEdge(nx)+bw
t = ROOT.TText(x2-bw/2,h5tev_chi_overf.GetBinContent(nx),"Overflow")
t.SetTextAngle(90)
t.SetTextAlign(12)
t.SetTextSize(0.03)
t.Draw("same")
leg.Draw()
c_over.Print('superimposition_overflow.pdf')

#c_eta = ROOT.TCanvas( 'c_eta', '')
#c_eta.Divide(2,1)
#c_eta.cd(1)
#h5tev_LeptonEta.Scale(1/h5tev_LeptonEta.Integral())
#h1tev_at8tev_LeptonEta.Scale(1/h1tev_at8tev_LeptonEta.Integral())
#h1tev_at13tev_LeptonEta.Scale(1/h1tev_at13tev_LeptonEta.Integral())
##h5tev_LeptonEta.Rebin(5)
##h1tev_at8tev_LeptonEta.Rebin(5)
##h1tev_at13tev_LeptonEta.Rebin(5)
#h5tev_LeptonEta.SetLineColor(6)
#h5tev_LeptonEta.SetLineWidth(2)
#h1tev_at8tev_LeptonEta.SetLineColor(1)
#h1tev_at8tev_LeptonEta.SetLineWidth(2)
#h1tev_at13tev_LeptonEta.SetLineColor(3)
#h1tev_at13tev_LeptonEta.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_LeptonEta.Draw("HISTO")
#h1tev_at8tev_LeptonEta.Draw("same histo")
#h1tev_at13tev_LeptonEta.Draw("same histo")
#c_eta.cd(2)
#h5tev_LeptonEta_MassRange.Scale(1/h5tev_LeptonEta_MassRange.Integral())
#h1tev_at8tev_LeptonEta_MassRange.Scale(1/h1tev_at8tev_LeptonEta_MassRange.Integral())
#h1tev_at13tev_LeptonEta_MassRange.Scale(1/h1tev_at13tev_LeptonEta_MassRange.Integral())
##h5tev_LeptonEta.Rebin(5)
##h1tev_at8tev_LeptonEta.Rebin(5)
##h1tev_at13tev_LeptonEta.Rebin(5)
#h5tev_LeptonEta_MassRange.SetLineColor(6)
#h5tev_LeptonEta_MassRange.SetLineWidth(2)
#h1tev_at8tev_LeptonEta_MassRange.SetLineColor(1)
#h1tev_at8tev_LeptonEta_MassRange.SetLineWidth(2)
#h1tev_at13tev_LeptonEta_MassRange.SetLineColor(3)
#h1tev_at13tev_LeptonEta_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_LeptonEta_MassRange.GetYaxis().SetRangeUser(0, 0.04)
##h5tev_prob.GetYaxis().SetLog()
#h5tev_LeptonEta_MassRange.Draw("HISTO")
#h1tev_at8tev_LeptonEta_MassRange.Draw("same histo")
#h1tev_at13tev_LeptonEta_MassRange.Draw("same histo")
#
#leg.Draw()
#c_eta.Print('superimposition_eta.pdf')
#
#c_vtxprob = ROOT.TCanvas( 'c_vtxprob', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
#pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
#pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
#pad1.Draw()
#pad2.Draw()
#pad3.Draw()
#pad4.Draw()
#pad1.cd()
#pad1.SetLogy()
#h5tev_prob_BB.Scale(1/h5tev_prob_BB.Integral())
#h1tev_at8tev_prob_BB.Scale(1/h1tev_at8tev_prob_BB.Integral())
#h1tev_at13tev_prob_BB.Scale(1/h1tev_at13tev_prob_BB.Integral())
#h5tev_prob_BB.Rebin(10)
#h1tev_at8tev_prob_BB.Rebin(10)
#h1tev_at13tev_prob_BB.Rebin(10)
#h5tev_prob_BB.SetLineColor(6)
#h5tev_prob_BB.SetLineWidth(2)
#h1tev_at8tev_prob_BB.SetLineColor(1)
#h1tev_at8tev_prob_BB.SetLineWidth(2)
#h1tev_at13tev_prob_BB.SetLineColor(3)
#h1tev_at13tev_prob_BB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_BB.Draw("HISTO")
#h1tev_at8tev_prob_BB.Draw("same histo")
#h1tev_at13tev_prob_BB.Draw("same histo")
#pad2.cd()
#pad2.SetLogy()
#h5tev_prob_EE.Scale(1/h5tev_prob_EE.Integral())
#h1tev_at8tev_prob_EE.Scale(1/h1tev_at8tev_prob_EE.Integral())
#h1tev_at13tev_prob_EE.Scale(1/h1tev_at13tev_prob_EE.Integral())
#h5tev_prob_EE.Rebin(10)
#h1tev_at8tev_prob_EE.Rebin(10)
#h1tev_at13tev_prob_EE.Rebin(10)
#h5tev_prob_EE.SetLineColor(6)
#h5tev_prob_EE.SetLineWidth(2)
#h1tev_at8tev_prob_EE.SetLineColor(1)
#h1tev_at8tev_prob_EE.SetLineWidth(2)
#h1tev_at13tev_prob_EE.SetLineColor(3)
#h1tev_at13tev_prob_EE.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_EE.Draw("HISTO")
#h1tev_at8tev_prob_EE.Draw("same histo")
#h1tev_at13tev_prob_EE.Draw("same histo")
#leg.Draw()
#pad3.cd()
#pad3.SetLogy()
#h5tev_prob_EB.Scale(1/h5tev_prob_EB.Integral())
#h1tev_at8tev_prob_EB.Scale(1/h1tev_at8tev_prob_EB.Integral())
#h1tev_at13tev_prob_EB.Scale(1/h1tev_at13tev_prob_EB.Integral())
#h5tev_prob_EB.Rebin(10)
#h1tev_at8tev_prob_EB.Rebin(10)
#h1tev_at13tev_prob_EB.Rebin(10)
#h5tev_prob_EB.SetLineColor(6)
#h5tev_prob_EB.SetLineWidth(2)
#h1tev_at8tev_prob_EB.SetLineColor(1)
#h1tev_at8tev_prob_EB.SetLineWidth(2)
#h1tev_at13tev_prob_EB.SetLineColor(3)
#h1tev_at13tev_prob_EB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_EB.Draw("HISTO")
#h1tev_at8tev_prob_EB.Draw("same histo")
#h1tev_at13tev_prob_EB.Draw("same histo")
#leg.Draw()
#c_vtxprob.Print('superimposition_vtxprob.pdf')
#
#c_vtxprob_m = ROOT.TCanvas( 'c_vtxprob_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
#pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
#pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
#pad1.Draw()
#pad2.Draw()
#pad3.Draw()
#pad4.Draw()
#pad1.cd()
#pad1.SetLogy()
#h5tev_prob_BB_MassRange.Scale(1/h5tev_prob_BB_MassRange.Integral())
#h1tev_at8tev_prob_BB_MassRange.Scale(1/h1tev_at8tev_prob_BB_MassRange.Integral())
#h1tev_at13tev_prob_BB_MassRange.Scale(1/h1tev_at13tev_prob_BB_MassRange.Integral())
#h5tev_prob_BB_MassRange.Rebin(10)
#h1tev_at8tev_prob_BB_MassRange.Rebin(10)
#h1tev_at13tev_prob_BB_MassRange.Rebin(10)
#h5tev_prob_BB_MassRange.SetLineColor(6)
#h5tev_prob_BB_MassRange.SetLineWidth(2)
#h1tev_at8tev_prob_BB_MassRange.SetLineColor(1)
#h1tev_at8tev_prob_BB_MassRange.SetLineWidth(2)
#h1tev_at13tev_prob_BB_MassRange.SetLineColor(3)
#h1tev_at13tev_prob_BB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_BB_MassRange.Draw("HISTO")
#h1tev_at8tev_prob_BB_MassRange.Draw("same histo")
#h1tev_at13tev_prob_BB_MassRange.Draw("same histo")
#pad2.cd()
#pad2.SetLogy()
#h5tev_prob_EE_MassRange.Scale(1/h5tev_prob_EE_MassRange.Integral())
#h1tev_at8tev_prob_EE_MassRange.Scale(1/h1tev_at8tev_prob_EE_MassRange.Integral())
#h1tev_at13tev_prob_EE_MassRange.Scale(1/h1tev_at13tev_prob_EE_MassRange.Integral())
#h5tev_prob_EE_MassRange.Rebin(10)
#h1tev_at8tev_prob_EE_MassRange.Rebin(10)
#h1tev_at13tev_prob_EE_MassRange.Rebin(10)
#h5tev_prob_EE_MassRange.SetLineColor(6)
#h5tev_prob_EE_MassRange.SetLineWidth(2)
#h1tev_at8tev_prob_EE_MassRange.SetLineColor(1)
#h1tev_at8tev_prob_EE_MassRange.SetLineWidth(2)
#h1tev_at13tev_prob_EE_MassRange.SetLineColor(3)
#h1tev_at13tev_prob_EE_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_EE_MassRange.Draw("HISTO")
#h1tev_at8tev_prob_EE_MassRange.Draw("same histo")
#h1tev_at13tev_prob_EE_MassRange.Draw("same histo")
#leg.Draw()
#pad3.cd()
#pad3.SetLogy()
#h5tev_prob_EB_MassRange.Scale(1/h5tev_prob_EB_MassRange.Integral())
#h1tev_at8tev_prob_EB_MassRange.Scale(1/h1tev_at8tev_prob_EB_MassRange.Integral())
#h1tev_at13tev_prob_EB_MassRange.Scale(1/h1tev_at13tev_prob_EB_MassRange.Integral())
#h5tev_prob_EB_MassRange.Rebin(10)
#h1tev_at8tev_prob_EB_MassRange.Rebin(10)
#h1tev_at13tev_prob_EB_MassRange.Rebin(10)
#h5tev_prob_EB_MassRange.SetLineColor(6)
#h5tev_prob_EB_MassRange.SetLineWidth(2)
#h1tev_at8tev_prob_EB_MassRange.SetLineColor(1)
#h1tev_at8tev_prob_EB_MassRange.SetLineWidth(2)
#h1tev_at13tev_prob_EB_MassRange.SetLineColor(3)
#h1tev_at13tev_prob_EB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob_EB_MassRange.Draw("HISTO")
#h1tev_at8tev_prob_EB_MassRange.Draw("same histo")
#h1tev_at13tev_prob_EB_MassRange.Draw("same histo")
#leg.Draw()
#c_vtxprob_m.Print('superimposition_vtxprob_massR.pdf')
#
#h5tev_MuonProbB_MassRange = d5tev.Get('DimuonMuonPtProb_Barrel_MassRange')
#h5tev_MuonProbE_MassRange = d5tev.Get('DimuonMuonPtProb_Endcap_MassRange')
#
#c_trkprob = ROOT.TCanvas( 'c_trkprob', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h5tev_MuonProbB.Scale(1/h5tev_MuonProbB.Integral())
#h1tev_at8tev_MuonProbB.Scale(1/h1tev_at8tev_MuonProbB.Integral())
#h1tev_at13tev_MuonProbB.Scale(1/h1tev_at13tev_MuonProbB.Integral())
#h5tev_MuonProbB.Rebin(10)
#h1tev_at8tev_MuonProbB.Rebin(10)
#h1tev_at13tev_MuonProbB.Rebin(10)
#h5tev_MuonProbB.SetLineColor(6)
#h5tev_MuonProbB.SetLineWidth(2)
#h1tev_at8tev_MuonProbB.SetLineColor(1)
#h1tev_at8tev_MuonProbB.SetLineWidth(2)
#h1tev_at13tev_MuonProbB.SetLineColor(3)
#h1tev_at13tev_MuonProbB.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonProbB.Draw("HISTO")
#h1tev_at8tev_MuonProbB.Draw("same histo")
#h1tev_at13tev_MuonProbB.Draw("same histo")
#leg.Draw()
#pad2.cd()
#pad2.SetLogy()
#h5tev_MuonProbE.Scale(1/h5tev_MuonProbE.Integral())
#h1tev_at8tev_MuonProbE.Scale(1/h1tev_at8tev_MuonProbE.Integral())
#h1tev_at13tev_MuonProbE.Scale(1/h1tev_at13tev_MuonProbE.Integral())
#h5tev_MuonProbE.Rebin(10)
#h1tev_at8tev_MuonProbE.Rebin(10)
#h1tev_at13tev_MuonProbE.Rebin(10)
#h5tev_MuonProbE.SetLineColor(6)
#h5tev_MuonProbE.SetLineWidth(2)
#h1tev_at8tev_MuonProbE.SetLineColor(1)
#h1tev_at8tev_MuonProbE.SetLineWidth(2)
#h1tev_at13tev_MuonProbE.SetLineColor(3)
#h1tev_at13tev_MuonProbE.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonProbE.Draw("HISTO")
#h1tev_at8tev_MuonProbE.Draw("same histo")
#h1tev_at13tev_MuonProbE.Draw("same histo")
#leg.Draw()
#
#c_trkprob.Print('superimposition_trkprob.pdf')
#
#c_trkprob_m = ROOT.TCanvas( 'c_trkprob_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h5tev_MuonProbB_MassRange.Scale(1/h5tev_MuonProbB_MassRange.Integral())
#h1tev_at8tev_MuonProbB_MassRange.Scale(1/h1tev_at8tev_MuonProbB_MassRange.Integral())
#h1tev_at13tev_MuonProbB_MassRange.Scale(1/h1tev_at13tev_MuonProbB_MassRange.Integral())
#h5tev_MuonProbB_MassRange.Rebin(10)
#h1tev_at8tev_MuonProbB_MassRange.Rebin(10)
#h1tev_at13tev_MuonProbB_MassRange.Rebin(10)
#h5tev_MuonProbB_MassRange.SetLineColor(6)
#h5tev_MuonProbB_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonProbB_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonProbB_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonProbB_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonProbB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonProbB_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonProbB_MassRange.Draw("same histo")
#h1tev_at13tev_MuonProbB_MassRange.Draw("same histo")
#leg.Draw()
#pad2.cd()
#pad2.SetLogy()
#h5tev_MuonProbE_MassRange.Scale(1/h5tev_MuonProbE_MassRange.Integral())
#h1tev_at8tev_MuonProbE_MassRange.Scale(1/h1tev_at8tev_MuonProbE_MassRange.Integral())
#h1tev_at13tev_MuonProbE_MassRange.Scale(1/h1tev_at13tev_MuonProbE_MassRange.Integral())
#h5tev_MuonProbE_MassRange.Rebin(10)
#h1tev_at8tev_MuonProbE_MassRange.Rebin(10)
#h1tev_at13tev_MuonProbE_MassRange.Rebin(10)
#h5tev_MuonProbE_MassRange.SetLineColor(6)
#h5tev_MuonProbE_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonProbE_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonProbE_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonProbE_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonProbE_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonProbE_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonProbE_MassRange.Draw("same histo")
#h1tev_at13tev_MuonProbE_MassRange.Draw("same histo")
#leg.Draw()
#
#c_trkprob_m.Print('superimposition_trkprob_massR.pdf')
#
#c_pterr_m = ROOT.TCanvas( 'c_pterr_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h5tev_MuonPtErrorB_MassRange.Scale(1/h5tev_MuonPtErrorB_MassRange.Integral())
#h1tev_at8tev_MuonPtErrorB_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorB_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorB_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorB_MassRange.Integral())
##h5tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorB_MassRange.Rebin(10)
#h5tev_MuonPtErrorB_MassRange.SetLineColor(6)
#h5tev_MuonPtErrorB_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorB_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorB_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorB_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonPtErrorB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonPtErrorB_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonPtErrorB_MassRange.Draw("same histo")
#h1tev_at13tev_MuonPtErrorB_MassRange.Draw("same histo")
#leg.Draw()
#pad2.cd()
#pad2.SetLogy()
#h5tev_MuonPtErrorE_MassRange.Scale(1/h5tev_MuonPtErrorE_MassRange.Integral())
#h1tev_at8tev_MuonPtErrorE_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorE_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorE_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorE_MassRange.Integral())
##h5tev_MuonPtErrorE_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorE_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorE_MassRange.Rebin(10)
#h5tev_MuonPtErrorE_MassRange.SetLineColor(6)
#h5tev_MuonPtErrorE_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorE_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorE_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorE_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonPtErrorE_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonPtErrorE_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonPtErrorE_MassRange.Draw("same histo")
#h1tev_at13tev_MuonPtErrorE_MassRange.Draw("same histo")
#leg.Draw()
#
#c_pterr_m.Print('superimposition_pterr_massR.pdf')
#
#
#c_pterrOver_m = ROOT.TCanvas( 'c_pterrOver_m', '')
#pad1 = TPad( 'pad1', '', 0.03, 0.03, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.03, 0.98, 0.95)
#pad1.Draw()
#pad2.Draw()
#
#pad1.cd()
#pad1.SetLogy()
#h5tev_MuonPtErrorOverPtB_MassRange.Scale(1/h5tev_MuonPtErrorOverPtB_MassRange.Integral())
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Integral())
##h5tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorB_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorB_MassRange.Rebin(10)
#h5tev_MuonPtErrorOverPtB_MassRange.SetLineColor(6)
#h5tev_MuonPtErrorOverPtB_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.04 )
#h5tev_MuonPtErrorOverPtB_MassRange.GetXaxis().SetRangeUser(0, 0.5 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonPtErrorOverPtB_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonPtErrorOverPtB_MassRange.Draw("same histo")
#h1tev_at13tev_MuonPtErrorOverPtB_MassRange.Draw("same histo")
#leg.Draw()
#pad2.cd()
#pad2.SetLogy()
#h5tev_MuonPtErrorOverPtE_MassRange.Scale(1/h5tev_MuonPtErrorOverPtE_MassRange.Integral())
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Scale(1/h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Integral())
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Scale(1/h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Integral())
##h5tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
##h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
##h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Rebin(10)
#h5tev_MuonPtErrorOverPtE_MassRange.SetLineColor(6)
#h5tev_MuonPtErrorOverPtE_MassRange.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.SetLineColor(1)
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.SetLineColor(3)
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
#h5tev_MuonPtErrorOverPtE_MassRange.GetXaxis().SetRangeUser(0, 0.5 )
##h5tev_prob.GetYaxis().SetLog()
#h5tev_MuonPtErrorOverPtE_MassRange.Draw("HISTO")
#h1tev_at8tev_MuonPtErrorOverPtE_MassRange.Draw("same histo")
#h1tev_at13tev_MuonPtErrorOverPtE_MassRange.Draw("same histo")
#leg.Draw()
#
#c_pterrOver_m.Print('superimposition_pterrOverpt_massR.pdf')
#
#
#c = ROOT.TCanvas( 'c', '')
##c.Divide(1,2)
##c.SetLogy()
#pad1 = TPad( 'pad1', '', 0.03, 0.50, 0.48, 0.95)
#pad2 = TPad( 'pad2', '', 0.50, 0.50, 0.98, 0.95)
#pad3 = TPad( 'pad3', '', 0.03, 0.02, 0.48, 0.48)
#pad4 = TPad( 'pad4', '', 0.50, 0.02, 0.98, 0.48)
#pad1.Draw()
#pad2.Draw()
#pad3.Draw()
#pad4.Draw()
#
#pad1.cd()
##pad1.SetLogy()
#h5tev.Scale(1/h5tev.Integral())
#h1tev_at8tev.Scale(1/h1tev_at8tev.Integral())
#h1tev_at13tev.Scale(1/h1tev_at13tev.Integral())
##h5tev.Rebin(10)
##h1tev_at8tev.Rebin(10)
##h1tev_at13tev.Rebin(10)
#
#h5tev.SetLineColor(6)
#h5tev.SetLineWidth(2)
#h1tev_at8tev.SetLineColor(1)
#h1tev_at8tev.SetLineWidth(2)
#h1tev_at13tev.SetLineColor(3)
#h1tev_at13tev.SetLineWidth(2)
#
#h1tev_at8tev.GetYaxis().SetRangeUser(0, 0.085)
#h1tev_at13tev.GetYaxis().SetRangeUser(0, 0.085)
#h5tev.GetYaxis().SetRangeUser(0, 0.085)
#h5tev.GetXaxis().SetRangeUser(0, 6200)
#h1tev_at8tev.GetXaxis().SetRangeUser(0, 6000)
#h1tev_at13tev.GetXaxis().SetRangeUser(0, 6000)
#h5tev.Draw("HISTO")
#h1tev_at8tev.Draw("same histo")
#h1tev_at13tev.Draw("same histo")
#                  #h5tev.Fit('gaus', '','',-0.1,0.1)
#leg.Draw()
#####################
#
#pad2.cd()
##pad2.SetLogy()
##p1->SetLogx();
#
##h5tev_Nvtx.Scale(1/h5tev_Nvtx.Integral())
##h1tev_at8tev_Nvtx.Scale(1/h1tev_at8tev_Nvtx.Integral())
##h1tev_at13tev_Nvtx.Scale(1/h1tev_at13tev_Nvtx.Integral())
##h5tev_Nvtx.Rebin(5)
##h1tev_at8tev_Nvtx.Rebin(5)
##h1tev_at13tev_Nvtx.Rebin(5)
##h5tev_Nvtx.SetLineColor(6)
##h5tev_Nvtx.SetLineWidth(2)
##h1tev_at8tev_Nvtx.SetLineColor(1)
##h1tev_at8tev_Nvtx.SetLineWidth(2)
##h1tev_at13tev_Nvtx.SetLineColor(3)
##h1tev_at13tev_Nvtx.SetLineWidth(2)
###h5tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_Nvtx.GetYaxis().SetRangeUser(0, 0.5)
###h5tev_prob.GetYaxis().SetLog()
##h5tev_Nvtx.Draw("HISTO")
##h1tev_at8tev_Nvtx.Draw("same histo")
##h1tev_at13tev_Nvtx.Draw("same histo")
##c.SetLogy();
#h5tev_LeptonEta.Scale(1/h5tev_LeptonEta.Integral())
#h1tev_at8tev_LeptonEta.Scale(1/h1tev_at8tev_LeptonEta.Integral())
#h1tev_at13tev_LeptonEta.Scale(1/h1tev_at13tev_LeptonEta.Integral())
##h5tev_LeptonEta.Rebin(5)
##h1tev_at8tev_LeptonEta.Rebin(5)
##h1tev_at13tev_LeptonEta.Rebin(5)
#h5tev_LeptonEta.SetLineColor(6)
#h5tev_LeptonEta.SetLineWidth(2)
#h1tev_at8tev_LeptonEta.SetLineColor(1)
#h1tev_at8tev_LeptonEta.SetLineWidth(2)
#h1tev_at13tev_LeptonEta.SetLineColor(3)
#h1tev_at13tev_LeptonEta.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_LeptonEta.GetYaxis().SetRangeUser(0, 0.5)
##h5tev_prob.GetYaxis().SetLog()
#h5tev_LeptonEta.Draw("HISTO")
#h1tev_at8tev_LeptonEta.Draw("same histo")
#h1tev_at13tev_LeptonEta.Draw("same histo")
#
#
#leg.Draw()
#
##########################
#pad3.cd()
#pad3.SetLogy()
##p1->SetLogx();
#
#h5tev_MuonProb.Scale(1/h5tev_MuonProb.Integral())
#h1tev_at8tev_MuonProb.Scale(1/h1tev_at8tev_MuonProb.Integral())
#h1tev_at13tev_MuonProb.Scale(1/h1tev_at13tev_MuonProb.Integral())
#h5tev_MuonProb.Rebin(10)
#h1tev_at8tev_MuonProb.Rebin(10)
#h1tev_at13tev_MuonProb.Rebin(10)
#
#h5tev_MuonProb.SetLineColor(6)
#h5tev_MuonProb.SetLineWidth(2)
#h1tev_at8tev_MuonProb.SetLineColor(1)
#h1tev_at8tev_MuonProb.SetLineWidth(2)
#h1tev_at13tev_MuonProb.SetLineColor(3)
#h1tev_at13tev_MuonProb.SetLineWidth(2)
##h5tev_MuonProb.GetYaxis().SetRangeUser(0, 0.085)
#h5tev_MuonProb.Draw("HISTO")
#h1tev_at8tev_MuonProb.Draw("same histo")
#h1tev_at13tev_MuonProb.Draw("same histo")
##########################
#
#pad4.cd()
#pad4.SetLogy()
##p1->SetLogx();
#
#h5tev_prob.Scale(1/h5tev_prob.Integral())
#h1tev_at8tev_prob.Scale(1/h1tev_at8tev_prob.Integral())
#h1tev_at13tev_prob.Scale(1/h1tev_at13tev_prob.Integral())
#h5tev_prob.Rebin(5)
#h1tev_at8tev_prob.Rebin(5)
#h1tev_at13tev_prob.Rebin(5)
#h5tev_prob.SetLineColor(6)
#h5tev_prob.SetLineWidth(2)
#h1tev_at8tev_prob.SetLineColor(1)
#h1tev_at8tev_prob.SetLineWidth(2)
#h1tev_at13tev_prob.SetLineColor(3)
#h1tev_at13tev_prob.SetLineWidth(2)
##h5tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
##h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_prob.GetYaxis().SetRangeUser(0, 0.3)
##h5tev_prob.GetYaxis().SetLog()
#h5tev_prob.Draw("HISTO")
#h1tev_at8tev_prob.Draw("same histo")
#h1tev_at13tev_prob.Draw("same histo")
##c.SetLogy();
#
#leg.Draw()
####################################
##pad3.cd()
##pad3.SetLogy()
###p1->SetLogx();
##
##h5tev_chi.Scale(1/h5tev_chi.Integral())
##h1tev_at8tev_chi.Scale(1/h1tev_at8tev_chi.Integral())
##h1tev_at13tev_chi.Scale(1/h1tev_at13tev_chi.Integral())
##h5tev_chi.Rebin(5)
##h1tev_at8tev_chi.Rebin(5)
##h1tev_at13tev_chi.Rebin(5)
##h5tev_chi.SetLineColor(6)
##h5tev_chi.SetLineWidth(2)
##h1tev_at8tev_chi.SetLineColor(1)
##h1tev_at8tev_chi.SetLineWidth(2)
##h1tev_at13tev_chi.SetLineColor(3)
##h1tev_at13tev_chi.SetLineWidth(2)
###h5tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetXaxis().SetRangeUser(0, 12)
###h1tev_at8tev_prob.GetYaxis().SetRangeUser(0, 0.3)
###h5tev_prob.GetYaxis().SetRangeUser(0, 0.3)
###h5tev_prob.GetYaxis().SetLog()
##h5tev_chi.Draw("HISTO")
##h1tev_at8tev_chi.Draw("same histo")
##h1tev_at13tev_chi.Draw("same histo")
##c.SetLogy();
#
#leg.Draw()
#
#c.Print('superimposition_zprime.pdf')
##
#
#c2 = ROOT.TCanvas( 'c2', '')
##c.Divide(1,2)
##c.SetLogy()
#pad11 = TPad( 'pad11', '', 0.03, 0.50, 0.48, 0.95)
#pad22 = TPad( 'pad22', '', 0.50, 0.50, 0.98, 0.95)
#pad33 = TPad( 'pad33', '', 0.03, 0.02, 0.48, 0.48)
#pad44 = TPad( 'pad44', '', 0.50, 0.02, 0.98, 0.48)
#pad11.Draw()
#pad22.Draw()
#pad33.Draw()
#pad44.Draw()
#
#pad11.cd()
#pad11.SetLogy()
#h5tev_MuonProb.Scale(1/h5tev_MuonProb.Integral())
#h1tev_at8tev_MuonProb.Scale(1/h1tev_at8tev_MuonProb.Integral())
#h1tev_at13tev_MuonProb.Scale(1/h1tev_at13tev_MuonProb.Integral())
##h5tev_MuonProb.Rebin(10)
##h1tev_at8tev_MuonProb.Rebin(10)
##h1tev_at13tev_MuonProb.Rebin(10)
#
#h5tev_MuonProb.SetLineColor(6)
#h5tev_MuonProb.SetLineWidth(2)
#h1tev_at8tev_MuonProb.SetLineColor(1)
#h1tev_at8tev_MuonProb.SetLineWidth(2)
#h1tev_at13tev_MuonProb.SetLineColor(3)
#h1tev_at13tev_MuonProb.SetLineWidth(2)
##h5tev_MuonProb.GetYaxis().SetRangeUser(0, 0.085)
#h5tev_MuonProb.Draw("HISTO")
#h1tev_at8tev_MuonProb.Draw("same histo")
#h1tev_at13tev_MuonProb.Draw("same histo")
##h5tev.Fit('gaus', '','',-0.1,0.1)
#leg.Draw()
#
#pad22.cd()
#pad22.SetLogy()
#h5tev_MuonPtErrOverPt.Scale(1/h5tev_MuonPtErrOverPt.Integral())
#h1tev_at8tev_MuonPtErrOverPt.Scale(1/h1tev_at8tev_MuonPtErrOverPt.Integral())
#h1tev_at13tev_MuonPtErrOverPt.Scale(1/h1tev_at13tev_MuonPtErrOverPt.Integral())
##h5tev_MuonPtErrOverPt.Rebin(10)
##h1tev_at8tev_MuonPtErrOverPt.Rebin(10)
## h1tev_at13tev_MuonPtErrOverPt.Rebin(10)
#
#h5tev_MuonPtErrOverPt.SetLineColor(6)
#h5tev_MuonPtErrOverPt.SetLineWidth(2)
#h1tev_at8tev_MuonPtErrOverPt.SetLineColor(1)
#h1tev_at8tev_MuonPtErrOverPt.SetLineWidth(2)
#h1tev_at13tev_MuonPtErrOverPt.SetLineColor(3)
#h1tev_at13tev_MuonPtErrOverPt.SetLineWidth(2)
#h5tev_MuonPtErrOverPt.GetXaxis().SetRangeUser(0, 0.5)
#h5tev_MuonPtErrOverPt.Draw("HISTO")
#h1tev_at8tev_MuonPtErrOverPt.Draw("same histo")
#h1tev_at13tev_MuonPtErrOverPt.Draw("same histo")
##h5tev.Fit('gaus', '','',-0.1,0.1)
#leg.Draw()
#
#c2.Print('superimposition2_zprime.pdf')
#
####ps = plot_saver('plots/resfromdy_new')
#
